# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-spektrum"
BBFILE_PATTERN_meta-spektrum = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-spektrum = "6"

LAYERDEPENDS_meta-spektrum = "core openembedded-layer"
LAYERSERIES_COMPAT_meta-spektrum = "scarthgap"
