# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "spektrum"
BBFILE_PATTERN_spektrum = "^${LAYERDIR}/"
BBFILE_PRIORITY_spektrum = "8"

LAYERDEPENDS_spektrum = "core openembedded-layer meta-python meta-tailscale"
LAYERSERIES_COMPAT_spektrum = "scarthgap styhead walnascar"
